name : first-action
on : workflow_dispatch
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print a greeting 
        run : echo "hello world!"
      - name: Print a goodbye
        run : echo "BYE!!!"
  
